# Generated by Django 5.1.15 on 2026-09-08 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la materia', max_length=150)),
                ('codigo', models.CharField(help_text='Código único de la materia (ej: MAT-101)', max_length=20, unique=True)),
                ('promedio_historico_promocion', models.FloatField(default=6.5, help_text='Promedio histórico de notas con el cual se promociona la materia (1.0 a 10.0)')),
                ('horas_cursada_semanal', models.FloatField(default=4.0, help_text='Horas semanales de cursada presencial/virtual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajo_semanal', models.FloatField(default=0.0, help_text='Cantidad de horas semanales dedicadas al trabajo u otras obligaciones.')),
                ('horas_sueno_objetivo', models.FloatField(default=8.0, help_text='Horas de sueño diarias deseadas/objetivo.')),
                ('promedio_general', models.FloatField(default=7.0, help_text='Promedio académico general del estudiante (1.00 a 10.00).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Usuario asociado al perfil del estudiante.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Estudiante',
                'verbose_name_plural': 'Perfiles de Estudiantes',
            },
        ),
    ]
