# Generated by Django 5.1.15 on 2026-09-08 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad_promocion_calculada', models.JSONField(default=dict, help_text='Estadísticas de probabilidad calculada por materia')),
                ('horas_estudio_sugeridas_dia', models.FloatField(default=0.0, help_text='Total de horas recomendadas de estudio diario')),
                ('nivel_riesgo', models.CharField(choices=[('Bajo', 'Bajo'), ('Equilibrado', 'Equilibrado'), ('Alto', 'Alto (Alto Riesgo)')], default='Equilibrado', help_text='Nivel de riesgo estimado de sobrecarga/desaprobación', max_length=20)),
                ('alerta_sobrecarga', models.BooleanField(default=False, help_text='Indica si la suma semanal de horas excede las 168h del reloj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('materias', models.ManyToManyField(help_text='Materias seleccionadas para la simulación del cuatrimestre', related_name='simulations', to='academic.subject')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='academic.studentprofile')),
            ],
            options={
                'verbose_name': 'Simulación de Inscripción',
                'verbose_name_plural': 'Simulaciones de Inscripción',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15)),
                ('horas_asignadas', models.FloatField(default=0.0, help_text='Horas de estudio planificadas para este día/materia')),
                ('cumplido', models.BooleanField(default=False, help_text='Feedback del alumno: True si cumplió el tiempo de estudio')),
                ('horas_reales_estudiadas', models.FloatField(blank=True, help_text='Feedback del alumno: Horas reales dedicadas', null=True)),
                ('resultado_obtenido', models.CharField(blank=True, help_text='Feedback del alumno: Calificación o desempeño percibido', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='academic.subject')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_items', to='assistant.enrollmentsimulation')),
            ],
            options={
                'verbose_name': 'Item de Plan de Estudio',
                'verbose_name_plural': 'Items de Plan de Estudio',
                'ordering': ['simulation', 'id'],
            },
        ),
    ]
